/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.virtualgamestore.gui.view;


import ec.edu.espe.virtualgamestore.controller.GamesReader;
import ec.edu.espe.virtualgamestore.model.Game;
import java.awt.Graphics;
import java.awt.Image;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author JavaMasters
 */
public class FrmGame extends javax.swing.JFrame {

    Background screen = new Background();

    /**
     * Creates new form FrmGame
     */
    public FrmGame() throws IOException {
        this.setContentPane(screen);
        GamesReader reader = new GamesReader();

        initComponents();
        setLocationRelativeTo(null);

        DefaultListModel JlstGames = new DefaultListModel();
        ArrayList<Game> games = new ArrayList<>();
        games = reader.readFromFile();

        for (Game game : games) {
            JlstGames.addElement(game.getName() + " ... " + game.getPegi() + " years ... " + game.getPrice() + "$");

        }
        JlistGames.setModel(JlstGames);

        ImageIcon icon = new ImageIcon(getClass().getResource("/ec/edu/espe/virtualgamestore/pictures/Console.png"));
        icon = new ImageIcon(icon.getImage().getScaledInstance(30, 30, Image.SCALE_DEFAULT));
        mnuConsole.setIcon(icon);

        ImageIcon icon3 = new ImageIcon(getClass().getResource("/ec/edu/espe/virtualgamestore/pictures/Toy.png"));
        icon3 = new ImageIcon(icon3.getImage().getScaledInstance(30, 30, Image.SCALE_DEFAULT));
        mnuToy.setIcon(icon3);

        ImageIcon icon4 = new ImageIcon(getClass().getResource("/ec/edu/espe/virtualgamestore/pictures/Headphones.png"));
        icon4 = new ImageIcon(icon4.getImage().getScaledInstance(30, 30, Image.SCALE_DEFAULT));
        mnuAccesory.setIcon(icon4);

        ImageIcon icon2 = new ImageIcon(getClass().getResource("/ec/edu/espe/virtualgamestore/pictures/GamesLogo.png"));
        icon2 = new ImageIcon(icon2.getImage().getScaledInstance(450, 80, Image.SCALE_DEFAULT));
        LbLogoGame.setIcon(icon2);

        ImageIcon icon5 = new ImageIcon(getClass().getResource("/ec/edu/espe/virtualgamestore/pictures/Cart.png"));
        icon5 = new ImageIcon(icon5.getImage().getScaledInstance(30, 30, Image.SCALE_DEFAULT));
        mnuCart.setIcon(icon5);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LbLogoGame = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JlistGames = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MnuVirtualGameStore = new javax.swing.JMenu();
        MnuMainMenu = new javax.swing.JMenuItem();
        MnuExit = new javax.swing.JMenuItem();
        mnuConsole = new javax.swing.JMenu();
        mnuAccesory = new javax.swing.JMenu();
        mnuToy = new javax.swing.JMenu();
        mnuCart = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        JlistGames.setBackground(new java.awt.Color(153, 153, 153));
        JlistGames.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jScrollPane2.setViewportView(JlistGames);

        MnuVirtualGameStore.setText("Virtual Game Store");

        MnuMainMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        MnuMainMenu.setText("Main Menu");
        MnuMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuMainMenuActionPerformed(evt);
            }
        });
        MnuVirtualGameStore.add(MnuMainMenu);

        MnuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        MnuExit.setText("Exit");
        MnuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuExitActionPerformed(evt);
            }
        });
        MnuVirtualGameStore.add(MnuExit);

        jMenuBar1.add(MnuVirtualGameStore);

        mnuConsole.setText("Consoles");
        mnuConsole.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuConsoleMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuConsole);

        mnuAccesory.setText("Accessories");
        mnuAccesory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuAccesoryMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuAccesory);

        mnuToy.setText("Toys");
        mnuToy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuToyMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuToy);

        mnuCart.setText("Cart");
        mnuCart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuCartMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuCart);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LbLogoGame, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel1))))
                .addContainerGap(205, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(LbLogoGame, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuToyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuToyMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        try {
            new FrmToy().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(FrmGame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnuToyMouseClicked

    private void mnuAccesoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuAccesoryMouseClicked
        this.setVisible(false);
        try {
            new FrmAccessory().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(FrmGame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnuAccesoryMouseClicked

    private void mnuConsoleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuConsoleMouseClicked
        this.setVisible(false);
        try {
            new FrmConsole().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(FrmGame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnuConsoleMouseClicked

    private void MnuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_MnuExitActionPerformed

    private void MnuMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuMainMenuActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new FrmPrincipalMenu().setVisible(true);
    }//GEN-LAST:event_MnuMainMenuActionPerformed

    private void mnuCartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuCartMouseClicked
        new FrmCart().setVisible(true);
        dispose();
    }//GEN-LAST:event_mnuCartMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrmGame().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(FrmGame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> JlistGames;
    private javax.swing.JLabel LbLogoGame;
    private javax.swing.JMenuItem MnuExit;
    private javax.swing.JMenuItem MnuMainMenu;
    private javax.swing.JMenu MnuVirtualGameStore;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenu mnuAccesory;
    private javax.swing.JMenu mnuCart;
    private javax.swing.JMenu mnuConsole;
    private javax.swing.JMenu mnuToy;
    // End of variables declaration//GEN-END:variables
class Background extends JPanel {

        private Image image;

        public void paint(Graphics g) {
            image = new ImageIcon(getClass().getResource("/ec/edu/espe/virtualgamestore/pictures/fontGame.jpeg")).getImage();

            g.drawImage(image, 0, 0, getWidth(), getHeight(), this);

            setOpaque(false);

            super.paint(g);
        }
    }
}
