/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.virtualgamestore.gui.view;

import Atxy2k.CustomTextField.RestrictedTextField;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import ec.edu.espe.virtualgamestore.model.User;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;

/**
 *
 * @author JavaMasters
 */
public class FrmRegister extends javax.swing.JFrame {

    JSONArray jsonUsers = new JSONArray();
    JSONArray jsonUserData = new JSONArray();

    /**
     * Creates new form FrmRegister
     */
    public FrmRegister() {
        initComponents();
        setLocationRelativeTo(null);
        RestrictedTextField restrict = new RestrictedTextField(ageTxt);
        restrict.setLimit(2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principalPnl = new javax.swing.JPanel();
        leftPnl = new javax.swing.JPanel();
        registerLbl = new javax.swing.JLabel();
        userLbl = new javax.swing.JLabel();
        userTxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        passwordTxt = new javax.swing.JLabel();
        passwordRegisterPswf = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        RegisterBTN = new javax.swing.JButton();
        sptRegister = new javax.swing.JSeparator();
        rightPnl = new javax.swing.JPanel();
        userPanelLeftLbl = new javax.swing.JLabel();
        emailLbl = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        emailTxt = new javax.swing.JTextField();
        ageLbl = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        ageTxt = new javax.swing.JTextField();
        returnPanel = new javax.swing.JPanel();
        ReturnBtn = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnMinimize = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        principalPnl.setBackground(new java.awt.Color(0, 0, 0));

        leftPnl.setBackground(new java.awt.Color(0, 0, 0));

        registerLbl.setBackground(new java.awt.Color(82, 59, 128));
        registerLbl.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        registerLbl.setForeground(new java.awt.Color(82, 59, 128));
        registerLbl.setText("Register");
        registerLbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        registerLbl.setVerifyInputWhenFocusTarget(false);

        userLbl.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        userLbl.setForeground(new java.awt.Color(255, 255, 255));
        userLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/virtualgamestore/pictures/UserIcon.png"))); // NOI18N
        userLbl.setText("USER");

        userTxt.setBackground(new java.awt.Color(0, 0, 0));
        userTxt.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        userTxt.setForeground(new java.awt.Color(255, 255, 255));
        userTxt.setBorder(null);
        userTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTxtActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(82, 59, 128));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        passwordTxt.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        passwordTxt.setForeground(new java.awt.Color(255, 255, 255));
        passwordTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/virtualgamestore/pictures/passwordIcon.png"))); // NOI18N
        passwordTxt.setText("PASSWORD");

        passwordRegisterPswf.setBackground(new java.awt.Color(0, 0, 0));
        passwordRegisterPswf.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        passwordRegisterPswf.setForeground(new java.awt.Color(102, 0, 153));
        passwordRegisterPswf.setBorder(null);
        passwordRegisterPswf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordRegisterPswfActionPerformed(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(82, 59, 128));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        RegisterBTN.setBackground(new java.awt.Color(92, 57, 163));
        RegisterBTN.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        RegisterBTN.setForeground(new java.awt.Color(92, 57, 163));
        RegisterBTN.setText("Register");
        RegisterBTN.setContentAreaFilled(false);
        RegisterBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RegisterBTN.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RegisterBTN.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        RegisterBTN.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                RegisterBTNMouseMoved(evt);
            }
        });
        RegisterBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegisterBTNMouseExited(evt);
            }
        });
        RegisterBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterBTNActionPerformed(evt);
            }
        });

        sptRegister.setForeground(new java.awt.Color(92, 57, 163));

        javax.swing.GroupLayout leftPnlLayout = new javax.swing.GroupLayout(leftPnl);
        leftPnl.setLayout(leftPnlLayout);
        leftPnlLayout.setHorizontalGroup(
            leftPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPnlLayout.createSequentialGroup()
                .addGroup(leftPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftPnlLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(registerLbl))
                    .addGroup(leftPnlLayout.createSequentialGroup()
                        .addGroup(leftPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(leftPnlLayout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addGroup(leftPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(userLbl)
                                    .addGroup(leftPnlLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(leftPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(passwordTxt)
                                            .addComponent(passwordRegisterPswf, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(leftPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(userTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, leftPnlLayout.createSequentialGroup()
                                                    .addGap(10, 10, 10)
                                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                            .addGroup(leftPnlLayout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addGroup(leftPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(leftPnlLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(sptRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(RegisterBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 91, Short.MAX_VALUE)))
                .addContainerGap())
        );
        leftPnlLayout.setVerticalGroup(
            leftPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPnlLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(registerLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(userLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(passwordTxt)
                .addGap(2, 2, 2)
                .addComponent(passwordRegisterPswf, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(RegisterBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sptRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        rightPnl.setBackground(new java.awt.Color(102, 0, 153));

        userPanelLeftLbl.setBackground(new java.awt.Color(0, 0, 0));
        userPanelLeftLbl.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        userPanelLeftLbl.setText("User");
        userPanelLeftLbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        userPanelLeftLbl.setVerifyInputWhenFocusTarget(false);

        emailLbl.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        emailLbl.setForeground(new java.awt.Color(255, 255, 255));
        emailLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/virtualgamestore/pictures/email_Ico.png"))); // NOI18N
        emailLbl.setText("E-mail");

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        emailTxt.setBackground(new java.awt.Color(102, 0, 153));
        emailTxt.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        emailTxt.setForeground(new java.awt.Color(255, 255, 255));
        emailTxt.setBorder(null);
        emailTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTxtActionPerformed(evt);
            }
        });

        ageLbl.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        ageLbl.setForeground(new java.awt.Color(255, 255, 255));
        ageLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/virtualgamestore/pictures/Age_Ico.png"))); // NOI18N
        ageLbl.setText("Age");

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        ageTxt.setBackground(new java.awt.Color(102, 0, 153));
        ageTxt.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        ageTxt.setForeground(new java.awt.Color(255, 255, 255));
        ageTxt.setBorder(null);
        ageTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageTxtActionPerformed(evt);
            }
        });
        ageTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ageTxtKeyTyped(evt);
            }
        });

        returnPanel.setBackground(new java.awt.Color(0, 0, 0));

        ReturnBtn.setBackground(new java.awt.Color(0, 0, 0));
        ReturnBtn.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        ReturnBtn.setForeground(new java.awt.Color(255, 255, 255));
        ReturnBtn.setText("Return");
        ReturnBtn.setBorderPainted(false);
        ReturnBtn.setContentAreaFilled(false);
        ReturnBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ReturnBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ReturnBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ReturnBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ReturnBtnMouseMoved(evt);
            }
        });
        ReturnBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ReturnBtnMouseExited(evt);
            }
        });
        ReturnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout returnPanelLayout = new javax.swing.GroupLayout(returnPanel);
        returnPanel.setLayout(returnPanelLayout);
        returnPanelLayout.setHorizontalGroup(
            returnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returnPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ReturnBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        returnPanelLayout.setVerticalGroup(
            returnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ReturnBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btnExit.setBackground(new java.awt.Color(0, 0, 0));
        btnExit.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        btnExit.setText("X");
        btnExit.setBorderPainted(false);
        btnExit.setContentAreaFilled(false);
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnMinimize.setBackground(new java.awt.Color(0, 0, 0));
        btnMinimize.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        btnMinimize.setText("-");
        btnMinimize.setBorderPainted(false);
        btnMinimize.setContentAreaFilled(false);
        btnMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rightPnlLayout = new javax.swing.GroupLayout(rightPnl);
        rightPnl.setLayout(rightPnlLayout);
        rightPnlLayout.setHorizontalGroup(
            rightPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userPanelLeftLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMinimize)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExit)
                .addGap(117, 117, 117))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightPnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(rightPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(166, 166, 166))
            .addGroup(rightPnlLayout.createSequentialGroup()
                .addGroup(rightPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rightPnlLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(rightPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ageLbl)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(ageTxt)))
                    .addGroup(rightPnlLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(returnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(rightPnlLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(emailLbl)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rightPnlLayout.setVerticalGroup(
            rightPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPnlLayout.createSequentialGroup()
                .addGroup(rightPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rightPnlLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(userPanelLeftLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(rightPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnExit)
                        .addComponent(btnMinimize)))
                .addGap(27, 27, 27)
                .addComponent(emailLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(ageLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ageTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(returnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout principalPnlLayout = new javax.swing.GroupLayout(principalPnl);
        principalPnl.setLayout(principalPnlLayout);
        principalPnlLayout.setHorizontalGroup(
            principalPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(principalPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(leftPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rightPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );
        principalPnlLayout.setVerticalGroup(
            principalPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leftPnl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rightPnl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(principalPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 890, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principalPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void userTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTxtActionPerformed

    private void passwordRegisterPswfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordRegisterPswfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordRegisterPswfActionPerformed

    private void emailTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTxtActionPerformed

    private void ageTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageTxtActionPerformed

    private void RegisterBTNMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterBTNMouseMoved
        RegisterBTN.setForeground(new java.awt.Color(34, 24, 56));
    }//GEN-LAST:event_RegisterBTNMouseMoved

    private void RegisterBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterBTNMouseExited
        RegisterBTN.setForeground(new java.awt.Color(92, 57, 163));
    }//GEN-LAST:event_RegisterBTNMouseExited

    private void RegisterBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterBTNActionPerformed
        JSONObject object = new JSONObject();
        JSONParser jsonParser = new JSONParser();
        JSONObject object2 = new JSONObject();
        JSONParser jsonParser2 = new JSONParser();

        try {
            FileReader fileUserData = new FileReader("UserData.json");
            jsonUserData = (JSONArray) jsonParser.parse(fileUserData);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error has ocurred");
        }
         try {
            FileReader fileUsers= new FileReader("Users.json");
            jsonUsers = (JSONArray) jsonParser2.parse(fileUsers);

        } catch (Exception ex) {
            
        }

        object.put("Password", passwordRegisterPswf.getText());
        object.put("Email", emailTxt.getText());
        object2.put("name", userTxt.getText());
        object2.put("Password", passwordRegisterPswf.getText());
        object.put("Age", ageTxt.getText());
        object.put("name", userTxt.getText());
        object.put("Password", passwordRegisterPswf.getText());
        jsonUserData.add(object);
         jsonUsers.add(object2);

        //////////////////////////////////////////////////////////////////////////
        File file2 = null;
        FileReader fileReader = null;
        BufferedReader bufferReader = null;
        ArrayList<User> name = new ArrayList<>();
        Gson gson = new Gson();
        String line;
        String userJson = "";
        try {

            file2 = new File("Users.json");
            fileReader = new FileReader(file2);
            bufferReader = new BufferedReader(fileReader);

            while ((line = bufferReader.readLine()) != null) {
                System.out.println(line);

                userJson = userJson + line;

            }
            userJson = userJson.replace("\\", "");
            //JOptionPane.showMessageDialog(rootPane, toysJson);
            java.lang.reflect.Type usersType = new TypeToken<ArrayList<User>>() {
            }.getType();

            name = gson.fromJson(userJson, usersType);

            for (User userName : name) {
                if (userTxt.getText().equals(userName.getName())) {
                    JOptionPane.showMessageDialog(null, "Your user is already in"
                            + " use, please choose another user");
                    return;
                }

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "error" + e.getMessage());
        } finally {
            try {
                if (null != fileReader) {
                    fileReader.close();
                }
            } catch (IOException e2) {
            }

        }
        ////////////////////////////////////////////////////////////////////////////////

        try {
            FileWriter file = new FileWriter("Users.json");
            file.write(jsonUsers.toJSONString());
            FileWriter fileUsersData = new FileWriter("UserData.json");
            fileUsersData.write(jsonUserData.toJSONString());
            file.close();
            fileUsersData.close();
        } catch (Exception ex) {
            
        }
        JOptionPane.showMessageDialog(null, "Your User Is Register");
        FrmLogIn frmLogIn = new FrmLogIn();
        frmLogIn.setVisible(true);
        dispose();
    }//GEN-LAST:event_RegisterBTNActionPerformed

    private void ReturnBtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReturnBtnMouseMoved
        returnPanel.setBackground(new java.awt.Color(34, 24, 56));
    }//GEN-LAST:event_ReturnBtnMouseMoved

    private void ReturnBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReturnBtnMouseExited
        returnPanel.setBackground(new java.awt.Color(92, 57, 163));
    }//GEN-LAST:event_ReturnBtnMouseExited

    private void ReturnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnBtnActionPerformed
        FrmLogIn frmLogIn = new FrmLogIn();
        frmLogIn.setVisible(true);
        dispose();

    }//GEN-LAST:event_ReturnBtnActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnMinimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizeActionPerformed
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btnMinimizeActionPerformed

    private void ageTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ageTxtKeyTyped
        char validation = evt.getKeyChar();
        if (Character.isLetter(validation)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Insert Only Numbers Please");
        }
    }//GEN-LAST:event_ageTxtKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RegisterBTN;
    private javax.swing.JButton ReturnBtn;
    private javax.swing.JLabel ageLbl;
    private javax.swing.JTextField ageTxt;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnMinimize;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPanel leftPnl;
    private javax.swing.JPasswordField passwordRegisterPswf;
    private javax.swing.JLabel passwordTxt;
    private javax.swing.JPanel principalPnl;
    private javax.swing.JLabel registerLbl;
    private javax.swing.JPanel returnPanel;
    private javax.swing.JPanel rightPnl;
    private javax.swing.JSeparator sptRegister;
    private javax.swing.JLabel userLbl;
    private javax.swing.JLabel userPanelLeftLbl;
    private javax.swing.JTextField userTxt;
    // End of variables declaration//GEN-END:variables
}
