/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.virtualgamestore.gui.view;


import ec.edu.espe.virtualgamestore.controller.ToyReader;
import ec.edu.espe.virtualgamestore.model.Toy;
import java.awt.Graphics;
import java.awt.Image;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author JavaMasters
 */
public class FrmToy extends javax.swing.JFrame {
    Background screen = new Background();
    

    
   
    public FrmToy() throws IOException {
        this.setContentPane(screen);
        ToyReader reader =new ToyReader();

        initComponents();
        setLocationRelativeTo(null);

        DefaultListModel JlstToys = new DefaultListModel();
        ArrayList<Toy> toys=new ArrayList<>();
        toys=reader.readFromFile();
        

        for (Toy toy : toys) {
            JlstToys.addElement(toy.getId() + ": " + toy.getName() + ": " + "+" + toy.getSize()+ ": "+toy.getMaterial()+": " + toy.getPrice() + "$");

        }
        JlistToy.setModel(JlstToys);
        ImageIcon icon = new ImageIcon(getClass().getResource("/ec/edu/espe/virtualgamestore/pictures/Console.png"));
        icon = new ImageIcon(icon.getImage().getScaledInstance(30, 30, Image.SCALE_DEFAULT));
        mnuConsole.setIcon(icon);
        
        ImageIcon icon2 = new ImageIcon(getClass().getResource("/ec/edu/espe/virtualgamestore/pictures/Game.png"));
        icon2 = new ImageIcon(icon2.getImage().getScaledInstance(30, 30, Image.SCALE_DEFAULT));
        mnuGame.setIcon(icon2);
        
        
        ImageIcon icon4 = new ImageIcon(getClass().getResource("/ec/edu/espe/virtualgamestore/pictures/Headphones.png"));
        icon4 = new ImageIcon(icon4.getImage().getScaledInstance(30, 30, Image.SCALE_DEFAULT));
        mnuAccesory.setIcon(icon4);
        
        ImageIcon icon3 = new ImageIcon(getClass().getResource("/ec/edu/espe/virtualgamestore/pictures/ToysLogo.png"));
        icon3 = new ImageIcon(icon3.getImage().getScaledInstance(500, 100, Image.SCALE_DEFAULT));
        LbLogoToy.setIcon(icon3);
        
         ImageIcon icon5 = new ImageIcon(getClass().getResource("/ec/edu/espe/virtualgamestore/pictures/Cart.png"));
        icon5 = new ImageIcon(icon5.getImage().getScaledInstance(30, 30, Image.SCALE_DEFAULT));
        mnuCart.setIcon(icon5);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LbLogoToy = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JlistToy = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuVirtualGameStore = new javax.swing.JMenu();
        mnuMainMenu = new javax.swing.JMenuItem();
        mnuExit = new javax.swing.JMenuItem();
        mnuConsole = new javax.swing.JMenu();
        mnuGame = new javax.swing.JMenu();
        mnuAccesory = new javax.swing.JMenu();
        mnuCart = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        LbLogoToy.setMaximumSize(new java.awt.Dimension(500, 100));
        LbLogoToy.setMinimumSize(new java.awt.Dimension(500, 100));

        JlistToy.setBackground(new java.awt.Color(153, 153, 153));
        JlistToy.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jScrollPane1.setViewportView(JlistToy);

        mnuVirtualGameStore.setText("Virtual Game Store");

        mnuMainMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        mnuMainMenu.setText("Main Menu");
        mnuMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMainMenuActionPerformed(evt);
            }
        });
        mnuVirtualGameStore.add(mnuMainMenu);

        mnuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        mnuExit.setText("Exit");
        mnuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExitActionPerformed(evt);
            }
        });
        mnuVirtualGameStore.add(mnuExit);

        jMenuBar1.add(mnuVirtualGameStore);

        mnuConsole.setText("Consoles");
        mnuConsole.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuConsoleMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuConsole);

        mnuGame.setText("Games");
        mnuGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuGameMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuGame);

        mnuAccesory.setText("Accessories");
        mnuAccesory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuAccesoryMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuAccesory);

        mnuCart.setText("Cart");
        mnuCart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuCartMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuCart);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel9)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 172, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LbLogoToy, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LbLogoToy, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuAccesoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuAccesoryMouseClicked
       this.setVisible(false);
        try {
            new FrmAccessory().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(FrmToy.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnuAccesoryMouseClicked

    private void mnuGameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuGameMouseClicked
        this.setVisible(false);
        try {
            new FrmGame().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(FrmToy.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnuGameMouseClicked

    private void mnuConsoleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuConsoleMouseClicked
        this.setVisible(false);
        try {
            new FrmConsole().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(FrmToy.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnuConsoleMouseClicked

    private void mnuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuExitActionPerformed

    private void mnuMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMainMenuActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new FrmPrincipalMenu().setVisible(true);
    }//GEN-LAST:event_mnuMainMenuActionPerformed

    private void mnuCartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuCartMouseClicked
        new FrmCart().setVisible(true);
        dispose();
    }//GEN-LAST:event_mnuCartMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmToy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmToy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmToy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmToy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrmToy().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(FrmToy.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> JlistToy;
    private javax.swing.JLabel LbLogoToy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu mnuAccesory;
    private javax.swing.JMenu mnuCart;
    private javax.swing.JMenu mnuConsole;
    private javax.swing.JMenuItem mnuExit;
    private javax.swing.JMenu mnuGame;
    private javax.swing.JMenuItem mnuMainMenu;
    private javax.swing.JMenu mnuVirtualGameStore;
    // End of variables declaration//GEN-END:variables
   class Background extends JPanel {

        private Image image;

        public void paint(Graphics g) {
            image = new ImageIcon(getClass().getResource("/ec/edu/espe/virtualgamestore/pictures/fontToy.jpg")).getImage();

            g.drawImage(image, 0, 0, getWidth(), getHeight(), this);

            setOpaque(false);

            super.paint(g);
        }
    }
}
        
        
        
        
    


